/*
 * radio program API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"ListGet",
			strings.ToUpper("Get"),
			"/api/list",
			c.ListGet,
		},
		{
			"ProgramPut",
			strings.ToUpper("Put"),
			"/api/program",
			c.ProgramPut,
		},
	}
}

// ListGet - 未聴取の番組リストを取得します
func (c *DefaultApiController) ListGet(w http.ResponseWriter, r *http.Request) {

	//result, err := c.service.ListGet()
	_, err := c.service.ListGet()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	var programs []Program
	for i := 0; i < 10; i++ {
		p := Program{
			Id:     fmt.Sprint(i),
			Title:  fmt.Sprint("test", i),
			Detail: fmt.Sprint("detail", i),
			Url:    "xxxx",
		}
		programs = append(programs, p)
	}

	EncodeJSONResponse(programs, nil, w)
	//EncodeJSONResponse(result, nil, w)
}

// ProgramPut - 番組を聴取済みに更新します
func (c *DefaultApiController) ProgramPut(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	programId := query.Get("programId")
	result, err := c.service.ProgramPut(programId)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
