openapi: 3.0.0
info:
  title: radio program API
  version: 1.0.0
servers:
- url: http://localhost:8080/api/
paths:
  /list:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/program'
          description: 未聴取の番組リスト
      summary: 未聴取の番組リストを取得します
  /program:
    put:
      parameters:
      - description: 番組IDを指定します
        explode: true
        in: query
        name: programId
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: 更新が成功しました
      summary: 番組を聴取済みに更新します
components:
  schemas:
    program:
      example:
        id: id
        detail: detail
        title: title
        url: url
      properties:
        id:
          type: string
        title:
          type: string
        detail:
          type: string
        url:
          type: string
      required:
      - detail
      - id
      - title
      - utl
